"""Контракты взаимодействия модулей (typing.Protocol).

Слои зависят от контрактов, а не от конкретных реализаций:
    Controllers → Service-контракты → Repository-контракты → data_access (SQLite)
Модуль models.data_access удовлетворяет контрактам Repository структурно.
"""
from typing import Any, Mapping, Protocol, Sequence

Row = Mapping[str, Any]


class CarRepository(Protocol):
    """Доступ к данным об автомобилях."""

    def get_all_cars(self) -> Sequence[Row]: ...
    def get_car_by_id(self, car_id: int) -> Row | None: ...
    def find_cars_by_name(self, search_text: str) -> Sequence[Row]: ...
    def get_all_manufacturers(self) -> Sequence[Row]: ...
    def add_car(self, model_name: str, price: float, year: int, body_type: str,
                manufacturer_id: int, color: str | None = None) -> int: ...
    def update_car(self, car_id: int, model_name: str, price: float, year: int,
                   body_type: str, manufacturer_id: int, color: str | None) -> bool: ...
    def delete_car(self, car_id: int) -> bool: ...


class SaleRepository(Protocol):
    """Доступ к данным о продажах и справочникам продажи."""

    def get_sale_history(self) -> Sequence[Row]: ...
    def get_all_dealerships(self) -> Sequence[Row]: ...
    def get_all_employees(self, dealership_id: int | None = None) -> Sequence[Row]: ...
    def get_all_customers(self) -> Sequence[Row]: ...
    def get_all_cars(self) -> Sequence[Row]: ...
    def find_cars_by_name(self, search_text: str) -> Sequence[Row]: ...
    def get_stock_by_dealership(self, dealership_id: int) -> Sequence[Row]: ...
    def create_sale(self, dealership_id: int, employee_id: int, customer_id: int | None,
                    items: list[dict]) -> int: ...


class ReportRepository(Protocol):
    """Наборы данных для отчётов."""

    def sales_by_period(self, start_date: str, end_date: str) -> Sequence[Row]: ...
    def cars_by_manufacturer(self) -> Sequence[Row]: ...
    def stock_by_dealership(self, dealership_id: int) -> Sequence[Row]: ...


class BackupRepository(Protocol):
    """Резервное копирование базы данных."""

    def create_backup(self, destination: Any) -> Any: ...
    def restore_backup(self, source: Any) -> Any: ...


class CarServiceContract(Protocol):
    """Контракт сервиса автомобилей (его использует контроллер)."""

    def get_all_cars(self) -> Sequence[Row]: ...
    def get_car_by_id(self, car_id: int) -> Row | None: ...
    def search_cars(self, text: str) -> Sequence[Row]: ...
    def get_manufacturers(self) -> Sequence[Row]: ...
    def add_car(self, model_name: str, price: Any, year: Any, body_type: str,
                manufacturer_id: Any, color: str | None = None) -> int: ...
    def update_car(self, car_id: int, model_name: str, price: Any, year: Any,
                   body_type: str, manufacturer_id: Any, color: str | None = None) -> bool: ...
    def delete_car(self, car_id: int) -> None: ...


class SaleServiceContract(Protocol):
    """Контракт сервиса продаж (его использует контроллер)."""

    def get_sale_history(self) -> Sequence[Row]: ...
    def get_dealerships(self) -> Sequence[Row]: ...
    def get_employees(self, dealership_id: int | None) -> Sequence[Row]: ...
    def get_customers(self) -> Sequence[Row]: ...
    def search_cars(self, text: str) -> Sequence[Row]: ...
    def create_sale(self, dealership_id: Any, employee_id: Any, customer_id: Any,
                    items: list[dict]) -> int: ...
